name: CiCd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # lint
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      # format
      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      # build
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      # test
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      # benchmarks
      - name: benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
    env:
      RUST_BACKTRACE: 1
